/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import repositorio.repositoryEquipo;
import dominio.equipo;
import dominio.jugador;

/**
 *
 * @author HP1000
 */
public class Equipo extends javax.swing.JInternalFrame {

    repositoryEquipo equiporep = new repositoryEquipo();

    /**
     * Creates new form Equipo
     */
    public Equipo() {
        initComponents();
        llenarequipo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelequipos = new javax.swing.JPanel();
        txtnombreequipo = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtciudadorigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboserie = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnumjugadores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnumasistentes = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtnombretecnico = new javax.swing.JTextField();
        txtcedulatecnico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpasaportetecnico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtedadtecnico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetalles = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaequipos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelequipos.setBackground(new java.awt.Color(204, 204, 255));
        panelequipos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        panelequipos.setForeground(new java.awt.Color(102, 0, 255));
        panelequipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelequipos.add(txtnombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        panelequipos.add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelequipos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jLabel1.setText("Nombre :");
        panelequipos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        panelequipos.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel2.setText("Origen Ciudad:");
        panelequipos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        panelequipos.add(txtciudadorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        jLabel3.setText("Serie :");
        panelequipos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cboserie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "LEGA PRO" }));
        panelequipos.add(cboserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));

        jLabel4.setText("NumJugadores :");
        panelequipos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        panelequipos.add(txtnumjugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, -1));

        jLabel5.setText("NumAsistentes :");
        panelequipos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        panelequipos.add(txtnumasistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tecnico"));

        jLabel6.setText("Nombres & Apellidos: ");

        jLabel7.setText("Cèdula:");

        jLabel8.setText("Pasaporte :");

        jLabel9.setText("Edad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcedulatecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtnombretecnico))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpasaportetecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedadtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcedulatecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtpasaportetecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnombretecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtedadtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelequipos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 490, 150));

        jLabel10.setText("Detalles:");
        panelequipos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        txtdetalles.setColumns(20);
        txtdetalles.setRows(5);
        jScrollPane1.setViewportView(txtdetalles);

        panelequipos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 300, 60));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registros de equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaequipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id  Equipo", "Nombre", "Ciudad Origen", "Serie", "Num Jugadores", "Num Asistentes", "Detalles", "Tecnico C.I", "Tec. Nombres", "Tec. Edad", "Tec. Pasaporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaequipos.setToolTipText("");
        jScrollPane4.setViewportView(tablaequipos);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 820, 100));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelequipos, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
        editarequipo();
        Limpiar();
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        
       
            
        
        
        
        agregarequipo();
        Limpiar();

    }//GEN-LAST:event_btngrabarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void agregarequipo() {
      
       equipo equi = new equipo( 0,txtnombreequipo.getText(),txtciudadorigen.getText(),cboserie.getSelectedItem().toString(),Integer.parseInt(txtnumjugadores.getText()),Integer.parseInt(txtnumasistentes.getText()),txtdetalles.getText(),Integer.parseInt(txtcedulatecnico.getText()),txtnombretecnico.getText(),Integer.parseInt(txtedadtecnico.getText()),Integer.parseInt(txtpasaportetecnico.getText()));
    //   equipo equi= new equipo (txtciudadorigen.getText());
    
       
        
        equiporep.agregar(equi);
        System.out.println(equipo.id);
        llenarequipo();
        // llenarequipos();
    }

    public void editarequipo() {
        int te = Integer.parseInt(tablaequipos.getValueAt(tablaequipos.getSelectedRow(), 0).toString());
        
        equipo equi = new equipo( 0,txtnombreequipo.getText(),txtciudadorigen.getText(),cboserie.getSelectedItem().toString(),Integer.parseInt(txtnumjugadores.getText()),Integer.parseInt(txtnumasistentes.getText()),txtdetalles.getText(),Integer.parseInt(txtcedulatecnico.getText()),txtnombretecnico.getText(),Integer.parseInt(txtedadtecnico.getText()),Integer.parseInt(txtpasaportetecnico.getText()));
        // equipo equi= new equipo(te,txtciudadorigen.getText());
        equiporep.editar(te, equi);
        System.out.println(equipo.id);
        llenarequipo();
        // llenarequipos();
    }

    public void Eliminar() {
        int te = Integer.parseInt(tablaequipos.getValueAt(tablaequipos.getSelectedRow(), 0).toString());
        equiporep.eliminar(te);
        llenarequipo();
        // llenarequipos();
    }

    public void llenarequipo() {
        List<equipo> equi = equiporep.getEquipo();
        DefaultTableModel rt = (DefaultTableModel) tablaequipos.getModel();
        Object equip[] = new Object[11];
        rt.setRowCount(0);//para que no llene una tras otra 
        for (equipo eq : equi) {
            equip[0] = eq.getIdequipo();
            equip[1] = eq.getNombre();
             equip[2] = eq.getOrigen();
            equip[3] = eq.getSerie();
              equip[4] = eq.getNum_jugadores();
              equip[5] = eq.getNum_asistentes(); 
             equip[6] = eq.getDetalles();
              equip[7] = eq.getCedula();
              equip[8] = eq.getNombresApellidos();   
              equip[9] = eq.getEdad();
              equip[10] = eq.getPasaporte();
                
            rt.addRow(equip);
        }
        tablaequipos.setModel(rt);
    }

    /*   public void llenarequipos(){
        List<equipo> equi =equiporep.getEquipo();
         cboequipodebug.removeAllItems();
        cboequipoactual.removeAllItems();
       
        
        for(equipo eq : equi){
             cboequipodebug.addItem(eq.getNombre());
            cboequipoactual.addItem(eq.getNombre());
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */

    public void Limpiar() {

        txtnombreequipo.setText("");
        txtcedulatecnico.setText("");
        txtnombreequipo.setText("");
        txtedadtecnico.setText("");
        txtdetalles.setText("");
        txtnumasistentes.setText("");
        txtnumjugadores.setText("");
        txtpasaportetecnico.setText("");
        txtciudadorigen.setText("");
        txtnombretecnico.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btngrabar;
    private javax.swing.JComboBox<String> cboserie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelequipos;
    private javax.swing.JTable tablaequipos;
    private javax.swing.JTextField txtcedulatecnico;
    private javax.swing.JTextField txtciudadorigen;
    private javax.swing.JTextArea txtdetalles;
    private javax.swing.JTextField txtedadtecnico;
    private javax.swing.JTextField txtnombreequipo;
    private javax.swing.JTextField txtnombretecnico;
    private javax.swing.JTextField txtnumasistentes;
    private javax.swing.JTextField txtnumjugadores;
    private javax.swing.JTextField txtpasaportetecnico;
    // End of variables declaration//GEN-END:variables
}
