/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import javax.swing.table.DefaultTableModel;

import dominio.equipo;
import repositorio.repositoryEquipos;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author HP1000
 */
public class FrmEquipo extends javax.swing.JInternalFrame {

    repositoryEquipos equiporep = new repositoryEquipos();

    /**
     * Creates new form Equipo
     */
    public FrmEquipo() {
        initComponents();
         mostrar("");
        inhabilitar();
       // llenarequipos();
        //llenarequipo();

    }
 private String accion = "guardar";

    void ocultar_columnas() {
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    void inhabilitar() {
       
  txtidequipo.setEnabled(false);
        txtnombreequipo.setEnabled(false);
        txtdetalles.setEnabled(false);
        txtnumasistentes.setEnabled(false);
        cboserie.setEnabled(false);
       txtnombretecnico.setEnabled(false);
        txtnumjugadores.setEnabled(false);
        txtcedulatecnico.setEnabled(false);
        txtpasaportetecnico.setEnabled(false);
       txtedadtecnico.setEnabled(false);

       txtciudadorigen.setEnabled(false);
        btnguardar.setEnabled(false);
        btneliminar1.setEnabled(false);
        
        btnlimpiar.setEnabled(false);

        txtidequipo.setText("");
        txtnombreequipo.setText("");
        txtnombretecnico.setText("");
        txtcedulatecnico.setText("");
        txtciudadorigen.setText("");
        txtnumasistentes.setText("");
        txtnumjugadores.setText("");
        txtedadtecnico.setText("");
         txtdetalles.setText("");
    }

    void habilitar() {
            
  txtidequipo.setEnabled(false);
        txtnombreequipo.setEnabled(true);
        txtdetalles.setEnabled(true);
        txtnumasistentes.setEnabled(true);
        cboserie.setEnabled(true);
       txtnombretecnico.setEnabled(true);
        txtnumjugadores.setEnabled(true);
        txtcedulatecnico.setEnabled(true);
        txtpasaportetecnico.setEnabled(true);
       txtedadtecnico.setEnabled(true);

       txtciudadorigen.setEnabled(true);
        btnguardar.setEnabled(true);
        btneliminar1.setEnabled(true);
        
        btnlimpiar.setEnabled(true);

        txtidequipo.setText("");
        txtnombreequipo.setText("");
        txtnombretecnico.setText("");
        txtcedulatecnico.setText("");
        txtciudadorigen.setText("");
        txtnumasistentes.setText("");
        txtnumjugadores.setText("");
        txtedadtecnico.setText("");
       txtdetalles.setText("");
        

    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            repositoryEquipos func = new repositoryEquipos();
            modelo = func.mostrar(buscar);

            tablalistado.setModel(modelo);
            //ocultar_columnas();
            lbltotalregistros.setText("Total Registros " + Integer.toString(func.totalregistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

       

        getContentPane().setBackground(new java.awt.Color(255, 204, 153));
        //setForeground(new java.awt.Color(153,255,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelequipos = new javax.swing.JPanel();
        txtnombreequipo = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtciudadorigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboserie = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnumjugadores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnumasistentes = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtnombretecnico = new javax.swing.JTextField();
        txtcedulatecnico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpasaportetecnico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtedadtecnico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetalles = new javax.swing.JTextArea();
        txtidequipo = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar1 = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        btnsalir1 = new javax.swing.JButton();
        lbltotalregistros = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelequipos.setBackground(new java.awt.Color(204, 204, 255));
        panelequipos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        panelequipos.setForeground(new java.awt.Color(102, 0, 255));
        panelequipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombreequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreequipoActionPerformed(evt);
            }
        });
        txtnombreequipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreequipoKeyTyped(evt);
            }
        });
        panelequipos.add(txtnombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panelequipos.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelequipos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jLabel1.setText("Nombre :");
        panelequipos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("Origen Ciudad:");
        panelequipos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtciudadorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciudadorigenActionPerformed(evt);
            }
        });
        txtciudadorigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciudadorigenKeyTyped(evt);
            }
        });
        panelequipos.add(txtciudadorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        jLabel3.setText("Serie :");
        panelequipos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cboserie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "LEGA PRO" }));
        panelequipos.add(cboserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));

        jLabel4.setText("NumJugadores :");
        panelequipos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtnumjugadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumjugadoresKeyTyped(evt);
            }
        });
        panelequipos.add(txtnumjugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, -1));

        jLabel5.setText("NumAsistentes :");
        panelequipos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtnumasistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumasistentesActionPerformed(evt);
            }
        });
        txtnumasistentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumasistentesKeyTyped(evt);
            }
        });
        panelequipos.add(txtnumasistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tecnico"));

        jLabel6.setText("Nombres & Apellidos: ");

        txtnombretecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombretecnicoKeyTyped(evt);
            }
        });

        txtcedulatecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulatecnicoKeyTyped(evt);
            }
        });

        jLabel7.setText("Cèdula:");

        jLabel8.setText("Pasaporte :");

        txtpasaportetecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasaportetecnicoKeyTyped(evt);
            }
        });

        jLabel9.setText("Edad:");

        txtedadtecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadtecnicoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcedulatecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtnombretecnico))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpasaportetecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedadtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcedulatecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtpasaportetecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnombretecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtedadtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelequipos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 490, 150));

        jLabel10.setText("Detalles:");
        panelequipos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        txtdetalles.setColumns(20);
        txtdetalles.setRows(5);
        txtdetalles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdetallesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtdetalles);

        panelequipos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, 60));
        panelequipos.add(txtidequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 10));

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panelequipos.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablalistado);

        jLabel11.setText("Buscar");

        btnbuscar1.setBackground(new java.awt.Color(51, 51, 51));
        btnbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar1.setText("Buscar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        btneliminar1.setBackground(new java.awt.Color(51, 51, 51));
        btneliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar1.setText("Eliminar");
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        btnsalir1.setBackground(new java.awt.Color(51, 51, 51));
        btnsalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir1.setText("Salir");
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltotalregistros.setText("Registros");

        btnimprimir.setBackground(new java.awt.Color(51, 51, 51));
        btnimprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnimprimir)
                        .addGap(107, 107, 107)
                        .addComponent(btneliminar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnsalir1)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnlimpiar)
                                    .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnimprimir)
                    .addComponent(btnsalir1)
                    .addComponent(btneliminar1)
                    .addComponent(btnlimpiar))
                .addGap(34, 34, 34)
                .addComponent(lbltotalregistros)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelequipos, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelequipos, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        
        equipo dts = new equipo();
        repositoryEquipos func = new repositoryEquipos();

        dts.setNombre(txtnombreequipo.getText());
        dts.setOrigen(txtciudadorigen.getText());
        
         int seleccionado = cboserie.getSelectedIndex();
        dts.setSerie((String) cboserie.getItemAt(seleccionado));
        
         dts.setNum_jugadores(Integer.parseInt(txtnumjugadores.getText()));
       dts.setNum_asistentes(Integer.parseInt(txtnumasistentes.getText()));
        dts.setDetalles(txtdetalles.getText());
        
       dts.setCedula(Integer.parseInt(txtcedulatecnico.getText()));
       dts.setNombresApellidos(txtnombretecnico.getText());
       dts.setEdad(Integer.parseInt(txtedadtecnico.getText()));
        dts.setPasaporte(Integer.parseInt(txtpasaportetecnico.getText()));
        
      
        if (accion.equals("guardar")) {
            if (func.Grabar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "REGISTRO EXITOSO");
                mostrar("");
                inhabilitar();

            }

        } else if (accion.equals("editar")) {
            dts.setIdequipo(Integer.parseInt(txtidequipo.getText()));

            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "MODIFICACION EXITOSA");
                mostrar("");
                inhabilitar();
            }
        }
        
       
            
        
        
        
      //  agregarequipo();
        Limpiar();

    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        // TODO add your handling code here:
        btnguardar.setText("Editar");
        habilitar();

        btneliminar1.setEnabled(true);
        accion="editar";
        try {
            int fila = tablalistado.rowAtPoint(evt.getPoint());
            //int fila = tablalistado.getSelectedRow();
            System.err.println(""+fila);
            txtidequipo.setText(tablalistado.getValueAt(fila, 0).toString());
            System.err.println("" + txtidequipo.getText());
            if (txtidequipo.getText().equals("")) {
                btneliminar1.setEnabled(false);
            } else {
                btneliminar1.setEnabled(true);
            }
            txtnombreequipo.setText(tablalistado.getValueAt(fila, 1).toString());
            txtciudadorigen.setText(tablalistado.getValueAt(fila, 2).toString());
            cboserie.setSelectedItem(tablalistado.getValueAt(fila, 3).toString());
            txtnumjugadores.setText(tablalistado.getValueAt(fila, 4).toString());
           txtnumasistentes.setText(tablalistado.getValueAt(fila, 5).toString());
            txtdetalles.setText(tablalistado.getValueAt(fila, 6).toString());
            txtcedulatecnico.setText(tablalistado.getValueAt(fila, 7).toString());
             txtnombretecnico.setText(tablalistado.getValueAt(fila, 8).toString());
              txtedadtecnico.setText(tablalistado.getValueAt(fila, 9).toString());
               txtpasaportetecnico.setText(tablalistado.getValueAt(fila, 10).toString());
               
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_tablalistadoMouseClicked

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        // TODO add your handling code here:
        if (txtidequipo.getText() != ("")) {

            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "SEGURO DE ELIMINAR?", "Confirmar", 2);

            if (confirmacion == 0) {
                repositoryEquipos func = new repositoryEquipos();
                equipo dts = new equipo();

                dts.setIdequipo(Integer.parseInt(txtidequipo.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();

            }

        }
    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalir1ActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Listado de jugadores");
        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");
        try {
            tablalistado.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (java.awt.print.PrinterException e) {

            System.err.format("error, no puede imrimir %s %n", e.getMessage());
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtnombreequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreequipoActionPerformed

    private void txtciudadorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciudadorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadorigenActionPerformed

    private void txtcedulatecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulatecnicoKeyTyped
        // TODO add your handling code here:
        
            char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    
        
    }//GEN-LAST:event_txtcedulatecnicoKeyTyped

    private void txtpasaportetecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasaportetecnicoKeyTyped
        // TODO add your handling code here:
        
             char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtpasaportetecnicoKeyTyped

    private void txtedadtecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadtecnicoKeyTyped
        // TODO add your handling code here:
        
             char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtedadtecnicoKeyTyped

    private void txtnumjugadoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumjugadoresKeyTyped
        // TODO add your handling code here:
        
             char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtnumjugadoresKeyTyped

    private void txtnumasistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumasistentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumasistentesActionPerformed

    private void txtnumasistentesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumasistentesKeyTyped
        // TODO add your handling code here:
        
             char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtnumasistentesKeyTyped

    private void txtnombreequipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreequipoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }
    }//GEN-LAST:event_txtnombreequipoKeyTyped

    private void txtciudadorigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadorigenKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }
    }//GEN-LAST:event_txtciudadorigenKeyTyped

    private void txtdetallesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetallesKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }
    }//GEN-LAST:event_txtdetallesKeyTyped

    private void txtnombretecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombretecnicoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }
    }//GEN-LAST:event_txtnombretecnicoKeyTyped

    /*public void agregarequipo() {
      
       equipo equi = new equipo(0,txtnombreequipo.getText(),txtciudadorigen.getText(),cboserie.getSelectedItem().toString(),Integer.parseInt(txtnumjugadores.getText()),Integer.parseInt(txtnumasistentes.getText()),txtdetalles.getText(),Integer.parseInt(txtcedulatecnico.getText()),txtnombretecnico.getText(),Integer.parseInt(txtedadtecnico.getText()),Integer.parseInt(txtpasaportetecnico.getText()));
    //   equipo equi= new equipo (txtciudadorigen.getText());
    
       
        
        equiporep.agregar(equi);
        System.out.println(equipo.id);
        llenarequipo();
        // llenarequipos();
    }

    public void editarequipo() {
        int te = Integer.parseInt(tablaequipos.getValueAt(tablaequipos.getSelectedRow(), 0).toString());
        
        equipo equi = new equipo( 0,txtnombreequipo.getText(),txtciudadorigen.getText(),cboserie.getSelectedItem().toString(),Integer.parseInt(txtnumjugadores.getText()),Integer.parseInt(txtnumasistentes.getText()),txtdetalles.getText(),Integer.parseInt(txtcedulatecnico.getText()),txtnombretecnico.getText(),Integer.parseInt(txtedadtecnico.getText()),Integer.parseInt(txtpasaportetecnico.getText()));
        // equipo equi= new equipo(te,txtciudadorigen.getText());
        equiporep.editar(te, equi);
        System.out.println(equipo.id);
        llenarequipo();
        //llenarequipos();
    }

    public void Eliminar() {
        int te = Integer.parseInt(tablaequipos.getValueAt(tablaequipos.getSelectedRow(), 0).toString());
        equiporep.eliminar(te);
        llenarequipo();
        // llenarequipos();
    }

    public void llenarequipo() {
        List<equipo> equi = equiporep.getEquipo();
        DefaultTableModel rt = (DefaultTableModel) tablaequipos.getModel();
        Object equip[] = new Object[11];
        rt.setRowCount(0);//para que no llene una tras otra 
        for (equipo eq : equi) {
            equip[0] = eq.getIdequipo();
            equip[1] = eq.getNombre();
             equip[2] = eq.getOrigen();
            equip[3] = eq.getSerie();
              equip[4] = eq.getNum_jugadores();
              equip[5] = eq.getNum_asistentes(); 
             equip[6] = eq.getDetalles();
              equip[7] = eq.getCedula();
              equip[8] = eq.getNombresApellidos();   
              equip[9] = eq.getEdad();
              equip[10] = eq.getPasaporte();
                
            rt.addRow(equip);
        }
        tablaequipos.setModel(rt);
    }

    /*   public void llenarequipos(){
        List<equipo> equi =equiporep.getEquipo();
         cboequipodebug.removeAllItems();
        cboequipoactual.removeAllItems();
       
        
        for(equipo eq : equi){
             cboequipodebug.addItem(eq.getNombre());
            cboequipoactual.addItem(eq.getNombre());
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */

    public void Limpiar() {

        txtnombreequipo.setText("");
        txtcedulatecnico.setText("");
        txtnombreequipo.setText("");
        txtedadtecnico.setText("");
        txtdetalles.setText("");
        txtnumasistentes.setText("");
        txtnumjugadores.setText("");
        txtpasaportetecnico.setText("");
        txtciudadorigen.setText("");
        txtnombretecnico.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir1;
    private javax.swing.JComboBox<String> cboserie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JPanel panelequipos;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcedulatecnico;
    private javax.swing.JTextField txtciudadorigen;
    private javax.swing.JTextArea txtdetalles;
    private javax.swing.JTextField txtedadtecnico;
    private javax.swing.JTextField txtidequipo;
    private javax.swing.JTextField txtnombreequipo;
    private javax.swing.JTextField txtnombretecnico;
    private javax.swing.JTextField txtnumasistentes;
    private javax.swing.JTextField txtnumjugadores;
    private javax.swing.JTextField txtpasaportetecnico;
    // End of variables declaration//GEN-END:variables
}
