/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conexion.Conexion;
import dominio.equipo;
import dominio.jugador;
import dominio.transferencia;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositorio.repositoryTransferencia;
import repositorio.repositoryEquipos;
import dto.transferenciadto;

/**
 *
 * @author HP1000
 */
public class FrmTransferencia extends javax.swing.JInternalFrame {
repositoryEquipos equiporep=new   repositoryEquipos();
repositoryTransferencia tr =new repositoryTransferencia();
    /**
     * Creates new form Tramsferencia
     */
    public FrmTransferencia() {
        initComponents();
        llenarequipos();
        txtid_transferencia.setVisible(false);
        txtTransfer.setVisible(false);
        txtnombres2.setEnabled(false);
        txtapellidos2.setEnabled(false); 
        txtcotizacion2.setEnabled(false);
        txtValor.setEnabled(false);
          getContentPane().setBackground(new java.awt.Color(53,255,153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Porcentaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        txtporcentaje = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        cbomodotransferncia = new javax.swing.JComboBox<>();
        btnlimpiar = new javax.swing.JButton();
        txtid_transferencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtapellidos2 = new javax.swing.JTextField();
        txtnombres2 = new javax.swing.JTextField();
        Porcentaje1 = new javax.swing.JLabel();
        txtcotizacion2 = new javax.swing.JTextField();
        btnbuscarjugador = new javax.swing.JButton();
        btnbuscartransfer = new javax.swing.JButton();
        txtTransfer = new javax.swing.JTextField();
        btcalcular = new javax.swing.JButton();
        COTIZACION = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        fecha_transferencia = new com.toedter.calendar.JDateChooser();
        cboequipotransferencia = new javax.swing.JComboBox<>();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Traspaso"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TRANSFERENCIA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("FECHA :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel3.setText("DESCRIPCIÒN:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, 20));

        jLabel5.setText("EQUIPO TRANSFERENCIA :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 20));

        jLabel6.setText("MODO:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        Porcentaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Porcentaje.setForeground(new java.awt.Color(255, 255, 51));
        Porcentaje.setText("VALOR ADICIONAL :");
        jPanel2.add(Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, 20));

        jLabel9.setText("CEDULA:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(204, 0, 0));
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 130, -1));

        txtporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtporcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(txtporcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 60, 30));

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, 30));

        cbomodotransferncia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENTA", "PRESTAMO" }));
        cbomodotransferncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomodotransfernciaActionPerformed(evt);
            }
        });
        jPanel2.add(cbomodotransferncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 120, 30));

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 410, 90, 30));
        jPanel2.add(txtid_transferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, -1));

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 270, 90));

        jLabel4.setText("NOMBRES :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setText("APELLIDOS :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel2.add(txtapellidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 230, 30));
        jPanel2.add(txtnombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 30));

        Porcentaje1.setText("PORCENTAJE :");
        jPanel2.add(Porcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 20));

        txtcotizacion2.setForeground(new java.awt.Color(51, 0, 204));
        txtcotizacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcotizacion2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtcotizacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 120, 30));

        btnbuscarjugador.setText("...");
        btnbuscarjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarjugadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscarjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        btnbuscartransfer.setText("...");
        btnbuscartransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscartransferActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscartransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));
        jPanel2.add(txtTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 40, -1));

        btcalcular.setText("Calcular");
        btcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalcularActionPerformed(evt);
            }
        });
        jPanel2.add(btcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 40, 30));

        COTIZACION.setText("COTIZACION: ");
        jPanel2.add(COTIZACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 20));

        txtValor.setForeground(new java.awt.Color(204, 0, 0));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        jPanel2.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 30));
        jPanel2.add(fecha_transferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 30));

        cboequipotransferencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboequipotransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 120, 30));

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, 30));

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 320, 90, 30));

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void cbomodotransfernciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomodotransfernciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbomodotransfernciaActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c>'.'&c<'.')){
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
        }}
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnbuscarjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarjugadorActionPerformed
        // TODO add your handling code here:
       // ConsultarFutbolista(); Consulta a solo un jugador
       jugador jugador2=new jugador();
       jugador2.setIdjugador(Integer.parseInt(txtcedula.getText()));
       
       repositoryTransferencia dts = new repositoryTransferencia();
       List<jugador>jugador =  dts.getJugador(jugador2);
       
        for (jugador object : jugador) {
            txtid_transferencia.setText(String .valueOf(object.getIdjugador()));
            txtValor.setText(String.valueOf(object.getCotizacion()));
            txtnombres2.setText(String.valueOf(object.getNombres()));
            txtapellidos2.setText(String.valueOf(object.getApellidos()));
           
            
        }
       
       
    }//GEN-LAST:event_btnbuscarjugadorActionPerformed

    private void btnbuscartransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscartransferActionPerformed
        // TODO add your handling code here:
        //ConsultarTranfer();
        transferenciadto dto= new transferenciadto();
        dto.setId_transferencia(Integer.parseInt(txtcedula.getText()));
        
        repositoryTransferencia reTransferencia=new repositoryTransferencia();
        List<transferenciadto>jugadortransferido= reTransferencia.getJugadorTransferido(dto);
        for (transferenciadto object : jugadortransferido) {
             txtid_transferencia.setText(String .valueOf(object.getId_jugador()));
             txtdescripcion.setText(String.valueOf(object.getDescripcion()));
             txtTransfer.setText(String.valueOf(object.getId_transferencia()));
            
        cbomodotransferncia.setSelectedItem(object.getModo_transferencia().toString());
        
fecha_transferencia.setDate( object.getFecha_transferencia());
        
            txtValor.setText(String.valueOf(object.getCotizacion()));
            txtnombres2.setText(String.valueOf(object.getNombres()));
            txtapellidos2.setText(String.valueOf(object.getApellidos()));
            txtporcentaje.setText(String.valueOf(object.getPorcentaje()));
            txtcotizacion2.setText(String.valueOf(object.getCotizacion2()));
                        
        }
    }//GEN-LAST:event_btnbuscartransferActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        
        
         if (txtporcentaje.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR PORCENTAJE");
            txtporcentaje.requestFocus();
            return;
        }

        if (txtdescripcion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR EQUIPO TRANSFERENCIA");
            txtdescripcion.requestFocus();
            return;
        }
        transferencia transferencia= new transferencia();
        
      transferencia.setDescripcion(txtdescripcion.getText());
      transferencia.setValoragegado(Double.parseDouble(txtcotizacion2.getText()));
       transferencia.setPorcentaje(Integer.parseInt(txtporcentaje.getText()));
      // fecha arreglar 
      Calendar cal;
        int d,m,a;
        cal=fecha_transferencia.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;  
            
      transferencia.setFecha_transferencia(new Date (a,m,d));
  
         int seleccionado = cbomodotransferncia.getSelectedIndex();
        transferencia.setModotransferencia((String) cbomodotransferncia.getItemAt(seleccionado));
      
        seleccionado = cboequipotransferencia.getSelectedIndex();
        transferencia.setEquipotransferencia((String) cboequipotransferencia.getItemAt(seleccionado));
       transferencia.setId_jugador(Integer.parseInt(txtid_transferencia.getText()));


        //Grabar();
        
        repositoryTransferencia func = new repositoryTransferencia();
        func.grabar(transferencia);
                
        Limpiar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        //Modificar();
        //ConsultarTranfer();
        
           transferencia transferencia= new transferencia();
        
      transferencia.setDescripcion(txtdescripcion.getText());
      transferencia.setValoragegado(Double.parseDouble(txtcotizacion2.getText()));
       transferencia.setPorcentaje(Integer.parseInt(txtporcentaje.getText()));
      // fecha arreglar 
      Calendar cal;
        int d,m,a;
        cal=fecha_transferencia.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;  
            
      transferencia.setFecha_transferencia(new Date (a,m,d));
  
         int seleccionado = cbomodotransferncia.getSelectedIndex();
        transferencia.setModotransferencia((String) cbomodotransferncia.getItemAt(seleccionado));
      
        seleccionado = cboequipotransferencia.getSelectedIndex();
        transferencia.setEquipotransferencia((String) cboequipotransferencia.getItemAt(seleccionado));
       transferencia.setId_jugador(Integer.parseInt(txtid_transferencia.getText()));
       transferencia.setIdtransferencia(Integer.parseInt(txtTransfer.getText()));


        //Grabar();
        
        repositoryTransferencia func = new repositoryTransferencia();
        func.modificar(transferencia);
     
     
        Limpiar();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
       transferencia transferencia = new transferencia();
       transferencia.setIdtransferencia(Integer.parseInt(txtTransfer.getText()));
       
       repositoryTransferencia repTransferencia=new repositoryTransferencia();
       repTransferencia.eliminar(transferencia);
        Limpiar();
    }//GEN-LAST:event_btneliminarActionPerformed

    double cotizacion;
    private void btcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalcularActionPerformed
        // TODO add your handling code here:
        
        DecimalFormat format=new DecimalFormat("######.##");        
        cotizacion=(((Double.parseDouble(txtValor.getText()))*(Integer.parseInt(txtporcentaje.getText()))/100));
        
       // txtcotizacion2.setText(Double.valueOf(format.format(cotizacion)));
       txtcotizacion2.setText(String.valueOf(format.format(cotizacion)));
    }//GEN-LAST:event_btcalcularActionPerformed

    private void txtporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtporcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtporcentajeActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtcotizacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcotizacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcotizacion2ActionPerformed

   /*public void Eliminar() {
        Conexion con = new Conexion();
        try {
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("DELETE FROM transferencia WHERE id_transferencia =" + txtTransfer.getText());
            pst.executeQuery();
            JOptionPane.showConfirmDialog(this, "Transferencia de Jugador eliminada","Confirmación",2);
        } catch (SQLException exc) {
            //JOptionPane.showMessageDialog(null, exc.getMessage(), "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void Modificar(){
        Conexion con = new Conexion();
        try{
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("UPDATE transferencia SET fecha=?, modo_transferencia=?, "
                    + "equipo_transferencia=?,"
        + "descripcion=?, cotizacion=?, porcentaje=?, id_jugador=?  WHERE id_transferencia =?");
           
             Calendar cal;
        int d,m,a;
        cal=fecha_transferencia.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;    
            pst.setDate(1, new Date(a,m,d));
            pst.setString(2, cbomodotransferncia.getSelectedItem().toString());
              pst.setString(3, cboequipotransferencia.getSelectedItem().toString());
            pst.setString(4, txtdescripcion.getText());
            
            pst.setDouble(5, Double.parseDouble(txtcotizacion2.getText()));
            pst.setInt(6, Integer.parseInt(txtporcentaje.getText()));
            pst.setInt(7,Integer.parseInt(txtid_transferencia.getText()));
            pst.setInt(8,Integer.parseInt(txtTransfer.getText()));
            pst.executeQuery();
            
            JOptionPane.showConfirmDialog(this, "Transeferencia de Jugador ha sido editada","Confirmación",2);
        }
        catch(SQLException exc){
           // JOptionPane.showMessageDialog(null,exc.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
   public void Grabar() {
        
        try {
            Conexion con = new Conexion();
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("INSERT INTO transferencia( fecha, modo_transferencia, "
                    + "equipo_transferencia,descripcion, cotizacion, porcentaje, id_jugador ) "+
            "VALUES ( ?, ?, ?, ?, ?, ?, ?)");
            
            //pst.setInt(1, Integer.parseInt(id_jugador.getText()));
             Calendar cal;
        int d,m,a;
        cal=fecha_transferencia.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;    
            pst.setDate(1, new Date(a,m,d));
            pst.setString(2, cbomodotransferncia.getSelectedItem().toString());
            pst.setString(3, cboequipotransferencia.getSelectedItem().toString());
            pst.setString(4, txtdescripcion.getText());
            
            pst.setDouble(5, cotizacion);
            pst.setInt(6, Integer.parseInt(txtporcentaje.getText()));
            pst.setInt(7,Integer.parseInt(txtid_transferencia.getText()));
            
            pst.executeQuery();
         
            JOptionPane.showConfirmDialog(this, "Jugador ha sido Tranferido","Confirmación",2);
            
                     
        } catch (SQLException exc) {
          //  JOptionPane.showMessageDialog(null, exc, "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void ConsultarFutbolista(){
         Conexion con = new Conexion();
        try{
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareCall("SELECT id_jugador,nombres,apellidos,"
                    + "cotizacion FROM jugador where cedula = "+ txtcedula.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                txtid_transferencia.setText(rs.getString(1));// ref id de jugador
                txtnombres2.setText(rs.getString(2));
                txtapellidos2.setText(rs.getString(3));
                txtValor.setText(rs.getString(4));
                txtnombres2.setEnabled(false);
                txtapellidos2.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(null,"No se econtrò futbolista","BOOK NOT FOUND",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(SQLException exc){
           // JOptionPane.showMessageDialog(null,exc,"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void ConsultarTranfer(){
         Conexion con = new Conexion();
        try{
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareCall("SELECT j.id_jugador,j.nombres,j.apellidos,t.fecha,"
                    + "t.modo_transferencia,"
                    + "t.equipo_transferencia,t.descripcion,t.cotizacion,t.porcentaje,t.id_transferencia, j.cotizacion "
                    + "FROM jugador j "
                    + "inner join transferencia t on j.id_jugador=t.id_jugador "
                    + "where j.cedula = "+ txtcedula.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                txtid_transferencia.setText(rs.getString(1));// ref id de jugador
                txtnombres2.setText(rs.getString(2));
                txtapellidos2.setText(rs.getString(3));
                
                fecha_transferencia.setDate(Date.valueOf(rs.getString(4)));
                cbomodotransferncia.setSelectedItem(rs.getString(5));
                 cboequipotransferencia.setSelectedItem(rs.getString(6));
                txtdescripcion.setText(rs.getString(7));
                txtcotizacion2.setText(rs.getString(8));
                txtporcentaje.setText(rs.getString(9));
                txtTransfer.setText(rs.getString(10));
                txtValor.setText(rs.getString(11));
                
                  
            }
            else{
                JOptionPane.showMessageDialog(null,"Futbolista no ha sido transferido","BOOK NOT FOUND",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(SQLException exc){
            //JOptionPane.showMessageDialog(null,exc,"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }*/
    public void Limpiar() {
        txtid_transferencia.setText("");
        txtdescripcion.setText("");
        
        txtcedula.setText("");
        cbomodotransferncia.setSelectedIndex(-0);
        txtporcentaje.setText("");
        txtnombres2.setText(null);
        txtapellidos2.setText(null);
        txtcotizacion2.setText(null);
        txtporcentaje.setText(null);
       
        fecha_transferencia.setCalendar(null);
        txtValor.setText(null);
        
    }
         public void llenarequipos(){
         
        List<equipo> equi =equiporep.getEquipo();
        
        cboequipotransferencia.removeAllItems();  
       
        for(equipo eq : equi){
            
            cboequipotransferencia.addItem(eq.getNombre());
           
        }
     }
         
        

         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COTIZACION;
    private javax.swing.JLabel Porcentaje;
    private javax.swing.JLabel Porcentaje1;
    private javax.swing.JButton btcalcular;
    private javax.swing.JButton btnbuscarjugador;
    private javax.swing.JButton btnbuscartransfer;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cboequipotransferencia;
    private javax.swing.JComboBox<String> cbomodotransferncia;
    private com.toedter.calendar.JDateChooser fecha_transferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTransfer;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtapellidos2;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcotizacion2;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtid_transferencia;
    private javax.swing.JTextField txtnombres2;
    private javax.swing.JTextField txtporcentaje;
    // End of variables declaration//GEN-END:variables
}

