/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conexion.Conexion;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP1000
 */
public class RegistrosConsultas_Futbolistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrosConsultas_Futbolistas
     */
    public RegistrosConsultas_Futbolistas() {
        initComponents();
         getContentPane().setBackground(new java.awt.Color(53,255,153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnbuscar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablafutbolistas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rcedula = new javax.swing.JRadioButton();
        rpasaporte = new javax.swing.JRadioButton();
        rposicion = new javax.swing.JRadioButton();
        txtcedula = new javax.swing.JTextField();
        cboposicion = new javax.swing.JComboBox<>();
        txtpasaporte = new javax.swing.JTextField();
        btnimprimir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de Futbolistas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btncancelar.setText("SALIR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        Tablafutbolistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRES", "APELLIDOS", "EDAD", "PASAPORTE", "POSICION", "DEBUG", "ACTUAL", "COTIZACION", "CEDULA"
            }
        ));
        jScrollPane1.setViewportView(Tablafutbolistas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Consultas de Futbolistas");

        rcedula.setText("CEDULA");
        rcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcedulaActionPerformed(evt);
            }
        });

        rpasaporte.setText("PASAPORTE");
        rpasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpasaporteActionPerformed(evt);
            }
        });

        rposicion.setText("POSICIÒN");
        rposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rposicionActionPerformed(evt);
            }
        });

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        cboposicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELANTERO", "ARQUERO", "DEFENSA", "VOLANTE" }));

        txtpasaporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasaporteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rposicion)
                        .addGap(36, 36, 36)
                        .addComponent(cboposicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rpasaporte)
                            .addComponent(rcedula))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rcedula)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rpasaporte)
                    .addComponent(txtpasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rposicion)
                    .addComponent(cboposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnimprimir.setText("IMRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btncancelar)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbuscar)
                            .addComponent(btnimprimir)
                            .addComponent(btncancelar))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tablafutbolistas.getModel();
        model.setRowCount(0);
        Consultar(model);
        Limpiar();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void rcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcedulaActionPerformed
        txtpasaporte.setEnabled(false);
        cboposicion.setEnabled(false);
        txtcedula.setEnabled(true);

    }//GEN-LAST:event_rcedulaActionPerformed

    private void rpasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpasaporteActionPerformed
        txtpasaporte.setEnabled(true);
        cboposicion.setEnabled(false);
        txtcedula.setEnabled(false);
    }//GEN-LAST:event_rpasaporteActionPerformed

    private void rposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rposicionActionPerformed
        txtpasaporte.setEnabled(false);
        cboposicion.setEnabled(true);
        txtcedula.setEnabled(false);
    }//GEN-LAST:event_rposicionActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Listado de Futbolistas");
        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");
        try {
            Tablafutbolistas.print(JTable.PrintMode.NORMAL,header,footer);

        } catch (java.awt.print.PrinterException e ) {

            System.err.format("error, no puede imrimir %s %n",e.getMessage());
        }

    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c>'.'&c<'.')){
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
        }}
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtpasaporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasaporteKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c>'.'&c<'.')){
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
        }}
    }//GEN-LAST:event_txtpasaporteKeyTyped

    
     public void Consultar(DefaultTableModel model){
        String sql = "";
        if(rcedula.isSelected()){
            sql = "SELECT jugador.id_jugador,jugador.nombres,jugador.apellidos,jugador.edad,jugador.pasaporte,jugador.posicion,jugador.equipo_debug,jugador.equipo_actual,jugador.cotizacion,jugador.cedula FROM jugador  WHERE jugador.cedula = '" + txtcedula.getText().toUpperCase()+ "'";
        }
        if(rpasaporte.isSelected()){
            sql = "SELECT jugador.id_jugador,jugador.nombres,jugador.apellidos,jugador.edad,jugador.pasaporte,jugador.posicion,jugador.equipo_debug,jugador.equipo_actual,jugador.cotizacion,jugador.cedula FROM jugador  WHERE jugador.pasaporte = '" + txtpasaporte.getText().toUpperCase()+ "'";
        }
        if(rposicion.isSelected()){
            sql = "SELECT jugador.id_jugador,jugador.nombres,jugador.apellidos,jugador.edad,jugador.pasaporte,jugador.posicion,jugador.equipo_debug,jugador.equipo_actual,jugador.cotizacion,jugador.cedula FROM jugador  WHERE jugador.posicion = '" + cboposicion.getSelectedItem().toString()+ "'";
        }
        int c = 0;
        Object [] tabla = new Object[10];
        
        Conexion con = new Conexion();
        try{
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareCall(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                c = 0;
                while(c < tabla.length){
                    tabla[c] = rs.getString(c+1);
                    c++;
                }
                model.addRow(tabla);
            }
            Tablafutbolistas.setModel(model);
        }
        catch(SQLException exc){
            JOptionPane.showMessageDialog(null,exc.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
    
     public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)throws PrinterException{
          if (pageIndex==0){
            Graphics2D g2d=(Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX()+30,pageFormat.getImageableY()+30);
            jPanel1.printAll(graphics);
            return PAGE_EXISTS;
        }else{
            return NO_SUCH_PAGE;
            
}}
    
    
    public void Limpiar(){
        txtcedula.setText("");
         txtpasaporte.setText("");
        cboposicion.setSelectedIndex(-1);
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrosConsultas_Futbolistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrosConsultas_Futbolistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrosConsultas_Futbolistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrosConsultas_Futbolistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrosConsultas_Futbolistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablafutbolistas;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JComboBox<String> cboposicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rcedula;
    private javax.swing.JRadioButton rpasaporte;
    private javax.swing.JRadioButton rposicion;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtpasaporte;
    // End of variables declaration//GEN-END:variables
}
